AppSeleccion/mvcSeleccion/Controllers/MantenimientoController.cs
using SalarDb.CodeGen.BLL;
using SalarDb.CodeGen.Model;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace mvcSeleccion.Controllers
{
    public class MantenimientoController : Controller
    {
        // GET: Mantenimiento
        public ActionResult Index(string a = null, string type = null)
        {
            ViewBag.ListadoMantenimientos = BaseGlobal.GetMaestroList();
            ViewBag.action = a;
            return View();
        }

        public ActionResult AreaTematica(string a = null)
        {
            var listSubgrupos = BaseGlobal.GetMaestroGrupoList("TEMATICA");
            ViewBag.action = a;
            return View(listSubgrupos);
        }

        public ActionResult Edit(int? id, int padre)
        {
            int grupoLista = 0;
            ViewBag.ListadoMantenimientos = BaseGlobal.GetMaestroList();
            tbMaestroListasModel lista = new tbMaestroListasModel();

            tbMaestroListasBLL lotbMaestroListasBLL = new tbMaestroListasBLL();
            List<SelectListItem> listaSelect = new List<SelectListItem>();
            ViewBag.ListadoSubGrupos = new List<SelectListItem>();
            if (id.HasValue)
            {
                List<tbMaestroListasModel> list = new List<tbMaestroListasModel>();
                lista = lotbMaestroListasBLL.GetBycnID_Lista(id.Value);
                if (padre == (int)mvcSeleccion.BaseGlobal.GruposListas.AreaTematicaNivel)
                {
                    tbMaestroGruposBLL lotbMaestroGruposBLL = new tbMaestroGruposBLL();
                    var grupo = lotbMaestroGruposBLL.GetBycnID_GrupoLista(lista.cnID_GrupoLista);
                    if (grupo.cnGrupoPadre != 0)
                    {
                        list = lotbMaestroListasBLL.GetBycnID_GrupoLista(grupo.cnGrupoPadre);
                    }

                    grupoLista = lista.cnID_GrupoLista;
                    lista.cnID_GrupoLista = (int)BaseGlobal.GruposListas.AreaTematicaNivel;
                    var listSubgrupos = BaseGlobal.GetMaestroGrupoList("TEMATICA");
                    ViewBag.ListadoSubGrupos = listSubgrupos.Select(x => new SelectListItem() { Text = x.ctNombreGrupo, Value = x.cnID_GrupoLista.ToString() }).ToList();
                    lista.cnID_SubGrupoLista = grupoLista;
                }

                listaSelect.AddRange((from x in list select new SelectListItem() { Text = x.ctElemento, Value = x.cnID_Lista.ToString() }).ToList());
            }

            lista.cnOrden = lista.cnOrden ?? 1;

            ViewBag.ListadoPadres = listaSelect;

            return View("Edit", lista);
        }

        public ActionResult EditAreaTematica(int? id)
        {
            tbMaestroGruposBLL lotbMaestroGruposBLL = new tbMaestroGruposBLL();
            tbMaestroGruposModel lotbMaestroGruposModel = new tbMaestroGruposModel();
            if (id.HasValue)
            {
                lotbMaestroGruposModel = lotbMaestroGruposBLL.GetBycnID_GrupoLista(id.Value);
            }

            var listSubgrupos = BaseGlobal.GetMaestroGrupoList("TEMATICA");

            var list = listSubgrupos.Select(x => new SelectListItem() { Text = x.ctNombreGrupo, Value = x.cnID_GrupoLista.ToString() }).ToList();
            list.Insert(0, new SelectListItem() { Value = "0", Text = "Seleccionar" });
            ViewBag.ListadoAreasTematicas = list;

            return View(lotbMaestroGruposModel);
        }

        [HttpPost]
        public ActionResult Save(tbMaestroListasModel model)
        {
            try
            {
                if (model.cnID_GrupoLista == (int)BaseGlobal.GruposListas.AreaTematicaNivel)
                    model.cnID_GrupoLista = model.cnID_SubGrupoLista;

                tbMaestroListasBLL lotbMaestroListasBLL = new tbMaestroListasBLL();
                model.cnEstado = 1;
                if (model.cnID_Lista == 0)
                    model.cnID_Lista = lotbMaestroListasBLL.Insert(model);
                else
                {
                    lotbMaestroListasBLL.Update(model);
                }
            }
            catch
            {
            }

            return RedirectToAction("Index", new { a = "saved", i = model.cnID_Lista });
        }

        [HttpPost]
        public ActionResult SaveAreaTematica(tbMaestroGruposModel model)
        {
            try
            {
                tbMaestroGruposBLL lotbMaestroGruposBLL = new tbMaestroGruposBLL();
                model.cnEstado = 1;
                model.ctTipoGrupo = "TEMATICA";
                if (model.cnID_GrupoLista == 0)
                    model.cnID_GrupoLista = lotbMaestroGruposBLL.Insert(model);
                else
                {
                    lotbMaestroGruposBLL.Update(model);
                }
            }
            catch
            {
            }

            return RedirectToAction("AreaTematica", new { a = "saved", i = model.cnID_GrupoLista });
        }

        [HttpPost]
        public ActionResult DeleteList(int id)
        {
            try
            {
                tbMaestroListasBLL lotbMaestroListasBLL = new tbMaestroListasBLL();
                lotbMaestroListasBLL.Delete(id);

                return Json("OK");
            }
            catch
            {
                return Json("KO");
            }
        }

        [HttpPost]
        public ActionResult DeleteGrupo(int id)
        {
            try
            {
                tbMaestroGruposBLL lotbMaestroGruposBLL = new tbMaestroGruposBLL();
                lotbMaestroGruposBLL.Delete(id);

                return Json("OK");
            }
            catch
            {
                return Json("KO");
            }
        }
    }
}

AppSeleccion/mvcSeleccion/Views/Mantenimiento/AreaTematica.cshtml
@using GridMvc.Html
@model List<SalarDb.CodeGen.Model.tbMaestroGruposModel>
@{

    var grid = new WebGrid(canPage: true, rowsPerPage: 10);
    grid.Bind(Model, rowCount: Model.Count, autoSortAndPage: true);
    grid.Pager(mode: WebGridPagerModes.All);

}
@section view_scripts{
    <script type="text/javascript" src="@Url.Content("~/Scripts/view/MantenimientosAreaTematica.js")"></script>
}
<section class="content-header">
    <h1></h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li class="active">Área Temática</li>
    </ol>
</section>
<section class="content">

    <div class="box-body">
        <div class="panel panel-info">
            <div class="panel-heading"><h3>Área Temática</h3></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="btn-group">
                            <a href="#" class="btn btn-default" id="btnNuevo">Nuevo</a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="row">

                        @grid.GetHtml(tableStyle: "table table-bordered table-hover",
                      columns: grid.Columns
                    (
                                    grid.Column("cnID_GrupoLista", "ID"),
                                    grid.Column("ctNombreGrupo", "Texto"),
                              grid.Column("Acciones", format: @<text>
                                        <a href="@Url.Content("~/Mantenimiento/EditAreaTematica?id=" + item.cnID_GrupoLista)" class="btn-link">Editar</a>
                                        <a href="#" class="btn-link" onclick="deleteItem('@item.cnID_GrupoLista','@item.cnID_GrupoLista')">Eliminar</a>
                            </text>, style: "col3Width", canSort: false)
))

                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

@section inpage_scripts{
    <script type="text/javascript">

        function deleteItem(group, id) {

            bootboxConfirm('¿Está seguro de eliminar el registro?', function () {
                $.post('@Url.Content("~/Mantenimiento/DeleteGrupo")', { id: id },
                            function (resp) {
                                ShowResponseDelete(resp);
                                if (resp == "OK")
                                    location.href = "@Url.Content("~/Mantenimiento/AreaTematica")";

                            });
            });
            console.log(id);
        }

        @if (ViewBag.action == "saved")
    {
        <text>
        ShowResponse("OK");
        </text>
    }

        $("#btnNuevo").click(function () {
            location.href = "@Url.Content("~/Mantenimiento/EditAreaTematica")";
        })

    </script>
}

AppSeleccion/mvcSeleccion/Views/Mantenimiento/Edit.cshtml
@model SalarDb.CodeGen.Model.tbMaestroListasModel
@using System.Linq;
@{
    Layout = BaseGlobal._Layout;
    var editGrupo = false;
    if (Model.cnID_Lista == 0)
    {
        editGrupo = true;
    }
}
@section view_scripts{
    <script type="text/javascript" src="@Url.Content("~/Scripts/view/Mantenimiento.js")"></script>
}

<section class="content-header">

    @*<h1>Formación Académica</h1>*@

    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li class="active">Mantenimiento</li>
    </ol>
</section>
<section class="content">
    @using (Html.BeginForm("Save", "Mantenimiento", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
    {
        @Html.HiddenFor(model => model.cnID_Lista)

        <div class="box-body">
            <div class="panel panel-info">
                <div class="panel-heading"><h3>Mantenimiento</h3></div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4 divGrupo">
                            <div class="form-group ">
                                <label for="cnID_Mantenimiento">Grupo:</label>
                                @Html.DropDownListFor(model => model.cnID_GrupoLista, (List<SelectListItem>)ViewBag.ListadoMantenimientos, new { @class = "form-control", required = "" })

                            </div>
                        </div>
                        <div class="col-md-4 divSubgrupo">
                            <div class="form-group ">
                                <label for="cnID_Mantenimiento">Subgrupo:</label>
                                @Html.DropDownListFor(model => model.cnID_SubGrupoLista, (List<SelectListItem>)ViewBag.ListadoSubGrupos, new { @class = "form-control", required = "" })

                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cnID_Mantenimiento">Padre:</label>
                                @Html.DropDownListFor(model => model.cnID_ListaPadre, (List<SelectListItem>)ViewBag.ListadoPadres, new { @class = "form-control" })

                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="ctCarreraOtro">Texto:</label>
                                @Html.TextBoxFor(model => model.ctElemento, new { @class = "form-control text-uppercase", placeholder = "Texto", required = "" })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="ctCarreraOtro">Orden:</label>
                                @Html.TextBoxFor(model => model.cnOrden, new { @class = "form-control text-uppercase", placeholder = "Orden", required = "" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        @*<div class="col-md-4">
                                <div class="form-group">
                                    <label for="cnID_Mantenimiento">Estado:</label>
                                    @Html.DropDownListFor(model => model.cnEstado, new List<SelectListItem>()
                                    {
                                        new SelectListItem(){ Text="Activo", Value="1"},
                                        new SelectListItem(){ Text="Inactivo", Value="0"}
                                    }, new { @class = "form-control", required = "" })

                                </div>
                            </div>*@
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cnID_Carrera">Obligatorio</label>
                                @Html.CheckBoxFor(model => model.cnObligatorio)

                            </div>
                        </div>

                    </div>
                </div>

                <div class="box-footer text-center">

                    <button type="reset" class="btn btn-default" id="btnCancelar">Cancelar</button>
                    <button type="submit" class="btn btn-primary" id="btnGuardar">@( (Model.cnID_Lista == 0) ? "Guardar" : "Actualizar")</button>
                </div>
            </div>
        </div>

    }
</section>


@section inpage_scripts{
    <script type="text/javascript">
        $("#btnCancelar").click(function () {
            var url = '@Url.Content("~/Mantenimiento/Index/")';
            location.href = url;
        });

        @if (!editGrupo)
        {
            <text>
        $(".divGrupo").hide();
        </text>
        }
    </script>
}

AppSeleccion/mvcSeleccion/Views/Mantenimiento/EditAreaTematica.cshtml
@model SalarDb.CodeGen.Model.tbMaestroGruposModel
@using System.Linq;
@{
    Layout = BaseGlobal._Layout;

}
@section view_scripts{
    <script type="text/javascript" src="@Url.Content("~/Scripts/view/MantenimientoAreaTematicaDet.js")"></script>
}

<section class="content-header">

    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li class="active">Área Temática</li>
    </ol>
</section>
<section class="content">
    @using (Html.BeginForm("SaveAreaTematica", "Mantenimiento", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
    {
        @Html.HiddenFor(model => model.cnID_GrupoLista)

        <div class="box-body">
            <div class="panel panel-info">
                <div class="panel-heading"><h3>Área Temática</h3></div>
                <div class="panel-body">
                    <div class="row">


                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="ctCarreraOtro">Texto:</label>
                                @Html.TextBoxFor(model => model.ctNombreGrupo, new { @class = "form-control text-uppercase", placeholder = "Texto", required = "" })
                            </div>
                        </div>
                        <div class="col-md-4 divGrupo">
                            <div class="form-group ">
                                <label for="cnID_Mantenimiento">Padre:</label>
                                @Html.DropDownListFor(model => model.cnGrupoPadre, (List<SelectListItem>)ViewBag.ListadoAreasTematicas, new { @class = "form-control", required = "" })

                            </div>
                        </div>                       
                    </div>
                </div>

                <div class="box-footer text-center">
                    <button type="reset" class="btn btn-default" id="btnCancelar">Cancelar</button>
                    <button type="submit" class="btn btn-primary" id="btnGuardar">@( (Model.cnID_GrupoLista == 0) ? "Guardar" : "Actualizar")</button>
                </div>
            </div>
        </div>

    }
</section>


@section inpage_scripts{
    <script type="text/javascript">
        $("#btnCancelar").click(function () {
            var url = '@Url.Content("~/Mantenimiento/AreaTematica/")';
            location.href = url;
        });


    </script>
}

AppSeleccion/mvcSeleccion/Views/Mantenimiento/Index.cshtml
@section view_scripts{
    <script type="text/javascript" src="@Url.Content("~/Scripts/view/Mantenimientos.js")"></script>
}
<section class="content-header">
    <h1></h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li class="active">Mantenimientos</li>
    </ol>
</section>
<section class="content">

    <div class="box-body">
        <div class="panel panel-info">
            <div class="panel-heading"><h3>Mantenimientos</h3></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="btn-group">
                            <a href="#" class="btn btn-default" id="btnNuevo">Nuevo</a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="cnID_Mantenimiento">Mantenimiento:</label>
                            @Html.DropDownList("cnID_Mantenimiento", (List<SelectListItem>)ViewBag.ListadoMantenimientos, new { @class = "form-control" })

                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="cnID_Mantenimiento">&nbsp;</label>
                            <select class="form-control" id="ddlSubgrupos"></select>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <label for="cnID_Mantenimiento">&nbsp;</label>
                        <div class="form-group">
                            <a href="#" class="btn btn-success" id="btnBuscar">Buscar</a>
                        </div>
                    </div>
                </div>

                <div id="divListadoItems">

                </div>


            </div>
        </div>
    </div>
</section>

@section inpage_scripts{
    <script type="text/javascript">
@if (ViewBag.action == "saved")
{
    <text>
        ShowResponse("OK");
        </text>
}

        $("#btnNuevo").click(function () {
            location.href = "@Url.Content("~/Mantenimiento/Edit?padre=0")";
        })
    </script>
}