AppSeleccion/mvcSeleccion/Controllers/SeleccionController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SalarDb.CodeGen.BLL;
using SalarDb.CodeGen.Common;
using SalarDb.CodeGen.Model;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvcSeleccion.Controllers
{
    public class SeleccionController : WebControllerBase
    {
        // GET: Seleccion
        public ActionResult Index()
        {
            if (!BaseGlobal.IsLogged)
                return this.RedirectToLogin();

            return View();
        }

        public ActionResult Registro(string a)
        {
            bool newUser = Request.Params.Get("a") == "new";
            if (!newUser && BaseGlobal.UsuarioActual == null)
            {
                return this.RedirectToLogin();
            }

            tbCandidatoBLL lotbCandidatoBLL = new tbCandidatoBLL();
            tbCandidatoModel lotbCandidatoModel = new tbCandidatoModel();

            if (a != null)
            {
                lotbCandidatoModel = new tbCandidatoModel();
                lotbCandidatoModel.cfFechaNacimiento = DateTime.Now;
                lotbCandidatoModel.tbDocIdentidadModelList = new List<tbDocIdentidadModel>();
                lotbCandidatoModel.tbDocIdentidadModelList.Add(new tbDocIdentidadModel());
            }
            else
            {
                long cnID_Candidato = BaseGlobal.CandidatoActual.cnID_Candidato;
                lotbCandidatoModel = lotbCandidatoBLL.GetBycnID_Candidato(cnID_Candidato);
                lotbCandidatoModel.ctEmail = lotbCandidatoModel.ctEmail.Trim(); //BGuerra 30-05-2015
                BaseGlobal.CandidatoActual = lotbCandidatoModel;
                lotbCandidatoModel.tbDocIdentidadModelList = new List<tbDocIdentidadModel>();
                if (cnID_Candidato == 0)
                {
                    lotbCandidatoModel.tbDocIdentidadModelList.Add(new tbDocIdentidadModel());
                }
                else
                {
                    tbDocIdentidadBLL lotbDocIdentidadBLL = new tbDocIdentidadBLL();
                    var docs = lotbDocIdentidadBLL.GetBycnID_CandidatoList(cnID_Candidato);
                    lotbCandidatoModel.tbDocIdentidadModelList = docs;
                }
            }

            ViewBag.Paises = BaseGlobal.GetPaisListItem();
            ViewBag.Documentos = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.TiposDocumento);

            var sexos = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.Sexo);
            var estadosCiviles = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.EstadoCivil);

            sexos.RemoveAll(x => x.Value.Trim() == string.Empty && x.Text == BaseGlobal._ComboSeleccionar);
            estadosCiviles.RemoveAll(x => x.Value.Trim() == string.Empty && x.Text == BaseGlobal._ComboSeleccionar);

            ViewBag.SexoListado = sexos;
            ViewBag.EstadoCivilListado = estadosCiviles;

            return View(lotbCandidatoModel);
        }

        [HttpPost]
        public ActionResult SaveRegistro(string model, int[] tbDocIdentidadModelList_cnID_TipoDocumento, string[] tbDocIdentidadModelList_ctNumero)
        {
            IDbConnection con = dbSeleccionDbConnection.GetNewConnection();
            dbSeleccionDbTransaction tran = dbSeleccionDbTransaction.BeginTransaction();
            tran.Connection = con;

            try
            {
                tbCandidatoModel loCandidato = JsonConvert.DeserializeObject<tbCandidatoModel>(model, new IsoDateTimeConverter { DateTimeFormat = "dd/MM/yyyy" });
                if (loCandidato.cnID_Departamento == 0)
                    loCandidato.cnID_Departamento = BaseGlobal.DepartamentoOtros;
                if (loCandidato.cnID_Provincia == 0)
                    loCandidato.cnID_Provincia = BaseGlobal.ProvinciaOtros;
                if (loCandidato.cnID_Distrito == 0)
                    loCandidato.cnID_Distrito = BaseGlobal.DistritoOtros;

                loCandidato.tbDocIdentidadModelList = new List<tbDocIdentidadModel>();
                for (int i = 0; i < tbDocIdentidadModelList_cnID_TipoDocumento.Count(); i++)
                {
                    loCandidato.tbDocIdentidadModelList.Add(new tbDocIdentidadModel() { cnID_TipoDocumento = tbDocIdentidadModelList_cnID_TipoDocumento[i], ctNumero = tbDocIdentidadModelList_ctNumero[i] });
                }

                loCandidato.ctIPAcceso = BaseUtil.GetIPAddress();

                tbCandidatoBLL lotbCandidatoBLL = new tbCandidatoBLL();

                lotbCandidatoBLL.Transaction = tran;
                lotbCandidatoBLL.Transaction.Connection = con;

                loCandidato.ctEmail = loCandidato.ctEmail.Trim();
                loCandidato.ctClaveAcceso = BaseUtil.EncryptPassword(loCandidato.ctClaveAcceso);
                if (loCandidato.cnID_Candidato > 0)
                {
                    lotbCandidatoBLL.Update(loCandidato);
                }
                else
                {
                    loCandidato.cnID_Candidato = lotbCandidatoBLL.Insert(loCandidato);
                }
                /*
                tbUsuarioModel lotbUsuarioModel = new tbUsuarioModel();
                tbUsuarioBLL lotbUsuarioBLL = new tbUsuarioBLL();

                lotbUsuarioBLL.Transaction = tran;
                lotbUsuarioBLL.Transaction.Connection = con;

                lotbUsuarioModel = lotbUsuarioBLL.GetByctLogin(loCandidato.ctEmail);
                if (lotbUsuarioModel != null)
                {
                    lotbUsuarioModel.ctClave = BaseUtil.EncryptPassword(loCandidato.ctClaveAcceso);
                    lotbUsuarioModel.ctNombres = loCandidato.ctNombres;
                    lotbUsuarioModel.ctApellidos = loCandidato.ctApellidoPaterno;
                    lotbUsuarioModel.cnEstadoReg = true;
                    lotbUsuarioBLL.Update(lotbUsuarioModel);
                }
                else
                {
                    lotbUsuarioModel = new tbUsuarioModel();
                    lotbUsuarioModel.cnID_Perfil = 1;
                    lotbUsuarioModel.ctLogin = loCandidato.ctEmail;
                    lotbUsuarioModel.ctClave = BaseUtil.EncryptPassword(loCandidato.ctClaveAcceso);
                    lotbUsuarioModel.ctNombres = loCandidato.ctNombres;
                    lotbUsuarioModel.ctApellidos = loCandidato.ctApellidoPaterno;
                    lotbUsuarioModel.cnEstadoReg = true;
                    //lotbUsuarioBLL.Insert(lotbUsuarioModel);
                }
                */

                tbDocIdentidadBLL lotbDocIdentidadBLL = new tbDocIdentidadBLL();

                lotbDocIdentidadBLL.Transaction = tran;
                lotbDocIdentidadBLL.Transaction.Connection = con;

                lotbDocIdentidadBLL.Delete(loCandidato.cnID_Candidato);
                loCandidato.tbDocIdentidadModelList.ForEach(x =>
                {
                    x.cnID_Candidato = loCandidato.cnID_Candidato;
                    lotbDocIdentidadBLL.Insert(x);
                });


                tbMailBLL lotbMaildBLL = new tbMailBLL();

                lotbMaildBLL.Transaction = tran;
                lotbMaildBLL.Transaction.Connection = con;

                var mail = new tbMailModel();
                mail.cnID_TipoEmail = BaseGlobal.TipoMailPersonal;
                mail.ctMail = loCandidato.ctEmail;
                mail.cnID_Candidato = loCandidato.cnID_Candidato;
                lotbMaildBLL.Insert(mail);

                tran.Commit();

                return Json("OK");
            }
            catch
            {
                tran.Rollback();
                return Json("KO");
            }
        }

        public ActionResult DatosPersonales(string a)
        {
            bool newUser = Request.Params.Get("a") == "new";
            if (!newUser && BaseGlobal.UsuarioActual == null)
            {
                return this.RedirectToLogin();
            }

            tbCandidatoBLL lotbCandidatoBLL = new tbCandidatoBLL();
            tbCandidatoModel lotbCandidatoModel = new tbCandidatoModel();

            if (a != null)
            {
                lotbCandidatoModel = new tbCandidatoModel();
                lotbCandidatoModel.cfFechaNacimiento = DateTime.Now;

                lotbCandidatoModel.tbDocIdentidadModelList = new List<tbDocIdentidadModel>();
                lotbCandidatoModel.tbDocIdentidadModelList.Add(new tbDocIdentidadModel());

                lotbCandidatoModel.tbMailModelList = new List<tbMailModel>();
                lotbCandidatoModel.tbMailModelList.Add(new tbMailModel());
            }
            else
            {
                long cnID_Candidato = BaseGlobal.CandidatoActual.cnID_Candidato;
                lotbCandidatoModel = lotbCandidatoBLL.GetBycnID_Candidato(cnID_Candidato);
                lotbCandidatoModel.ctEmail = lotbCandidatoModel.ctEmail.Trim(); //BGuerra 30-05-2015
                BaseGlobal.CandidatoActual = lotbCandidatoModel;

                lotbCandidatoModel.tbDocIdentidadModelList = new List<tbDocIdentidadModel>();
                lotbCandidatoModel.tbMailModelList = new List<tbMailModel>();

                if (cnID_Candidato == 0)
                {
                    lotbCandidatoModel.tbDocIdentidadModelList.Add(new tbDocIdentidadModel());
                    lotbCandidatoModel.tbMailModelList.Add(new tbMailModel());
                }
                else
                {
                    tbDocIdentidadBLL lotbDocIdentidadBLL = new tbDocIdentidadBLL();
                    var docs = lotbDocIdentidadBLL.GetBycnID_CandidatoList(cnID_Candidato);
                    lotbCandidatoModel.tbDocIdentidadModelList = docs;

                    tbMailBLL lotbMaildBLL = new tbMailBLL();
                    var mails = lotbMaildBLL.GetBycnID_CandidatoList(cnID_Candidato);
                    lotbCandidatoModel.tbMailModelList = mails;

                    //agregar mails

AppSeleccion/mvcSeleccion/Views/Seleccion/AreaTematica.cshtml
@model SalarDb.CodeGen.Model.tbAreaTematicaModel
@using System.Linq;
@{
    Layout = BaseGlobal._Layout;
    int n = 2;
}
@section view_scripts{
    <link rel="stylesheet" href="@Url.Content("~/Content/css/bootstrap/css/bootstrap-tagsinput.css")" />


    <script type="text/javascript" src="@Url.Content("~/Scripts/bootstrap-tagsinput.min.js")"></script>


    <script type="text/javascript" src="@Url.Content("~/Scripts/view/AreaTematica.js")"></script>

}

@section css_styles{
    <style type="text/css">
        .bootstrap-tagsinput {
            width: 100%;
        }
    </style>
}

<section class="content-header">

    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li class="active">Áreas Temáticas</li>
    </ol>
</section>
<section class="content">

    <div class="box-body">
        <div class="panel panel-info">
            <div class="panel-heading"><h3>Área Temática</h3></div>
            <div class="panel-body">
                <div class="row">
                    <p>Áreas temáticas de dominio para el dictado de cursos:</p>
                    <div class="col-md-3">
                        <div class="form-group">
                            @*@Html.ListBox("ddlNivel_1", (List<SelectListItem>)ViewBag.Nivel1List, new { @class = "form-control ddlNormal ddlFirst", data_next_level = "2", current_level = 1, size = 10 })*@
                            @Html.ListBox("ddlNivel_1", (List<SelectListItem>)ViewBag.Nivel1List, new { @class = "form-control ddlNormal ddlLast", data_next_level = "2", current_level = 1, size = 10 })
                        </div>
                    </div>

                    @*<div class="col-md-3">
                        <div class="form-group">
                            @Html.ListBox("ddlNivel_2", (List<SelectListItem>)ViewBag.Nivel2, new { @class = "form-control ddlNormal ddlSecond", data_next_level = "3", current_level = 2, size = 10 })
                        </div>
                    </div>*@

                    @*<div class="col-md-3">
                        <div class="form-group">
                            <div id="chkLastLevelList">
                            </div>
                        </div>
                    </div>*@



                    @for (int i = 2; i <= n; i++)
                    {
                        if (i != n)
                        {
                            var last = (i == n - 1);
                            <div class="col-md-3">
                                <div class="form-group">

                                    @*@Html.ListBox("ddlNivel_" + @i, new List<SelectListItem>(), new { @class = "form-control ddlNormal" + (last ? " ddlLast" : ""), data_next_level = (i + 1), current_level = @i, size = 10 })*@
                                    @*@Html.ListBox("ddlNivel_" + @i, (List<SelectListItem>)ViewBag.Nivel1List, new { @class = "form-control ddlNormal" + (last ? " ddlLast" : ""), data_next_level = (i + 1), current_level = @i, size = 10 })*@

                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div id="chkLastLevelList">
                                    </div>
                                </div>
                            </div>
                        }
                    }






                </div>

                <div class="row">
                    <div class="box-footer text-center">
                        <button type="submit" class="btn btn-primary" id="btnGuardar">Guardar</button>
                    </div>
                </div>

                @Html.HiddenFor(model => model.cnID_AreaTematica)
                @Html.HiddenFor(model => model.cnID_Candidato)
                <div class="row">
                    <p>Áreas de Dominio Específico</p>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.TextBox("txtAreaEspecifica", "", new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-md-1">
                        <div class="form-group">
                            <button type="reset" class="btn btn-info" id="btnAgregar">Agregar</button>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.TextBox("ctDominioEspecifico", "", new { name = "ctDominioEspecifico", @class = "form-control", data_role = "tagsinput", width = "200px" })
                        </div>
                    </div>
                </div>




            </div>
        </div>
    </div>


</section>
@section inpage_scripts{
    <script>
        $(document).ready(function () {
            $("#ctDominioEspecifico").tagsinput('add', '@Model.ctDominioEspecifico');

            // Detectar qeu cambie el valor del select

           

            
            




                
            //if ($("#ddlNivel_3.from-control.ddlNormal.ddlLast").val() == null ) {
            //    bootbox.alert("Seleccione un area temática");
            //    return;
            //}

            //});

            //$('#ddlNivel_2').change(function () {
            //    var str = "";
            //    $('#ddlNivel_3').each(function () {
            //        str += $ddlNivel1.text() + "";
            //    });

            //$.each(selectValues, function (key, value) {
            //        $('#ddlNivel_2').append($("<Option ></Option>").attr("value".key).text(value));

            //    });


            //})
                // Pintar sys option en base al ViewBag.Nivel2
            //$('#ddlNivel_2').tagsinut('add', '')
             
        });

    </script>
}

AppSeleccion/mvcSeleccion/Views/Seleccion/Oportunidades.cshtml
@model List<SalarDb.CodeGen.Model.tbProcesoModel>

<section class="content-header">

    @*<h1>Oportunidades</h1>*@

    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li class="active">Listado de Oportunidades</li>
    </ol>
</section>
<section class="content">

    <div class="box-body">
        <div class="panel panel-info">
            <div class="panel-heading"><h3>Listado de Oportunidades</h3></div>
            <div class="panel-body">
                <div class="row">

                    <div class="col-md-12">
                        <section id="no-more-tables">
                            <table class="table table-striped table-hover" id="tab_crit_acad">
                                <thead>
                                    <tr>

                                        <th>Título</th>

                                        <th>Inicio</th>
                                        <th>Fin</th>
                                        <th>Términos de Referencia</th>
                                        <th>Estado</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @for (int i = 0; i < Model.Count; i++)
                                    {
                                        var item = Model[i];
                                        <tr>
                                            <td data-title="Título">@item.ctTitulo</td>

                                            <td data-title="Inicio">@item.cfFechaInicio</td>
                                            <td data-title="Fin">@item.cfFechaFin</td>
                                            <td data-title="Archivo Términos">                                                                                                
                                                <a href="#" class="btn btn-link lnkDescargar" data-filename="@item.ctArchivoTerminos">Ver</a>
                                            </td>
                                            <td data-title="Estado">
                                                @Html.ActionLink(item.EsPostulante ? "Ya te encuentras inscrito" : "Postular", item.EsPostulante ? "Postulacion" : "Postular", new { id = item.cnID_Proceso }, new { @class = "btn btn-link " + (item.EsPostulante ? "disabled" : "") })
                                            </td>
                                            <td data-title="Acciones">
                                                @if (item.EsPostulante)
                                                {
                                                    <a href="#" class="btn btn-link lnkAnular" data-id="@item.cnID_Proceso">Anular Postulación</a>
                                                }
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@Html.Hidden("hdnDownloadFileUrl", @Url.Content("~/Convocatoria/DownloadFile"))
@section inpage_scripts{
    <script type="text/javascript">

        $(window).ready(function () {

            $(".lnkDescargar").click(function () {
                var file = $(this).attr("data-filename");

                $.ajax({
                    url: $("#hdnDownloadFileUrl").val(),
                    type: 'GET',
                    data: {
                        file: file
                    },
                    //dataType: 'json',
                    //contentType: 'application/json; charset=utf-8',
                    success: function (response) {

                        if (response.result != undefined) {
                            bootboxError(response.result);
                            return;
                        }
                        //location.href = $("#hdnDownloadFileUrl").val() + "?file=" + file;
                        window.open($("#hdnDownloadFileUrl").val() + "?file=" + file, '_blank');
                    },
                    error: function () {
                        bootboxAlert("error");
                    }
                });

            })

        })


        @if (ViewBag.action == "saved")
        {
            <text>
        ShowResponse("OK", 'Usted ha postulado al proceso correctamente.');
        </text>
        }
        @if (ViewBag.action == "deleted")
        {
            <text>
        ShowResponse("OK", 'Usted ha anulado su postulación correctamente.');
        </text>
        }


        $(".lnkAnular").click(function () {
            var id = $(this).attr("data-id");
            bootboxConfirm('¿Está seguro de anular su postulación?', function () {
                var url = "@Url.Content("~/Seleccion/Anular?id=")" + id;
                location.href = url;
            });

        });
    </script>
}

AppSeleccion/mvcSeleccion/Views/Seleccion/Perfil.cshtml
@model SalarDb.CodeGen.Model.tbCandidatoModel
@section view_scripts{
    <script type="text/javascript" src="@Url.Content("~/Scripts/view/Perfil.js")"></script>
}
<section class="content">
    <!-- form start -->
    <style>
        .fillme{
          overflow:hidden;
        }
        .fillme img.stretchx{
          height:auto;
          width:100%;
        }
        .fillme img.stretchy{
          height:100%;
          width:auto;
        }
    </style>
    <div class="box-body">

        <div class="panel panel-info">
            @using (Html.BeginForm("SavePerfil", "Seleccion", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
            {
                @Html.HiddenFor(model => model.ctImagenPerfil)
                <div class="panel panel-info">
                    <div class="panel-heading"><h3>Perfil</h3></div>

                    <div class="panel-body">

                        <div class="row">
                            <div class="col-md-3">
                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 200px;">
                                        @if (!Model.ctImagenPerfil.IsEmpty())
                                        {
                                            <img style="height:100%; width:100%; overflow:hidden" src="@Url.Content("~/Uploads/Perfil/"+Model.ctImagenPerfil)" />
                                        }
                                    </div>
                                    <div>
                                        <span class="btn btn-default btn-file"><span class="fileinput-new">Cambiar foto</span><span class="fileinput-exists">Cambiar</span><input type="file" name="txtImagen"></span>
                                        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Eliminar</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label for="ctEmail">Tipo de Email:</label>
                                    @Html.DropDownListFor(model => model.cnID_TipoEmail, (List<SelectListItem>)ViewBag.TipoEmail, new { @class = "form-control", required = "" })
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="form-group">
                                    <label for="ctEmail">Email:</label>
                                    @Html.DropDownListFor(model => model.ctEmail, (ViewBag.Emails == null ? new List<SelectListItem>() : (List<SelectListItem>)ViewBag.Emails), new { @class = "form-control", placeholder = "Otro", required = "required" })
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="ctClaveAcceso">Ingresar Contraseña:</label>
                                            @Html.PasswordFor(model => model.ctClaveAcceso, new { @class = "form-control", placeholder = "Ingresar Contraseña", data_minlength = "6", maxlength = "15" })
                                            <span class="help-block">Ingrese mínimo 6 caracteres</span>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="ctClaveAcceso2">Repetir Contraseña:</label>
                                            <input type="password" name="ctClaveAcceso2" class="form-control" id="ctClaveAcceso2" placeholder="Repetir Contraseña" maxlength="15">
                                        </div>
                                    </div>
                                    <div class="col-md-4">


                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 p-3" style="margin-top:20px">
                                <div class="form-group">
                                    <label for="Descripcion">Presentación:</label>
                                    @Html.TextAreaFor(model => model.ctDescripcion, new { @class = "form-control", placeholder = "Ingrese su presentacion", required = "required", maxlength = "100" })
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="box-footer text-center">
                        @Html.HiddenFor(model => model.cnID_Candidato)

                        <button type="reset" class="btn btn-default" id="btnCancelar">Cancelar</button>
                        <button type="submit" class="btn btn-primary" id="btnGuardar">Guardar</button>
                    </div>
                </div>
            }
        </div>

    </div>
</section>

@section inpage_scripts{
    <script type="text/javascript">
        $(window).load(function () {

            $("#btnCancelar").click(function () {
                location.href = "@Url.Content("~/Auth/Welcome")";
            });


        });

    </script>
}