AppSeleccion/mvcSeleccion/Controllers/FormacionController.cs
using SalarDb.CodeGen.BLL;
using SalarDb.CodeGen.Model;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace mvcSeleccion.Controllers
{
    public class FormacionController : WebControllerBase
    {
        public ActionResult Academica(int? id, string a = null, int? i = null)
        {
            if (!BaseGlobal.IsLogged)
                return this.RedirectToLogin();

            long cnID_Candidato = BaseGlobal.CandidatoActual.cnID_Candidato;
            ViewBag.Grados = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.Grado, sort: false);
            ViewBag.Carreras = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.Carrera, addOtros: true);

            var instituciones = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.Instituto);
            instituciones.AddRange(BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.Universidad));
            instituciones.Sort((x, y) => x.Text.CompareTo(y.Text));
            instituciones.RemoveAll(x => x.Value.Trim() == string.Empty && x.Text == BaseGlobal._ComboSeleccionar);
            instituciones.Insert(0, new SelectListItem() { Text = BaseGlobal._ComboSeleccionar, Value = string.Empty });
            instituciones.Insert(1, new SelectListItem() { Text = BaseGlobal._ComboOtros, Value = BaseGlobal.Otros.ToString() });
            ViewBag.Instituciones = instituciones;

            ViewBag.Paises = BaseGlobal.GetPaisListItem();

            tbAcademicoBLL lotbAcademicoBLL = new tbAcademicoBLL();
            tbAcademicoModel lotbAcademicoModel = new tbAcademicoModel();
            lotbAcademicoModel.cnID_Candidato = cnID_Candidato;
            lotbAcademicoModel.cfFechaInicio = DateTime.Now;
            lotbAcademicoModel.cfFechaFin = DateTime.Now;
            lotbAcademicoModel.tbAcademicoModelList = new List<tbAcademicoModel>();

            if (id.HasValue)
            {
                if (id.Value > 0)
                {
                    lotbAcademicoModel = lotbAcademicoBLL.GetBycnID_Academico(id.Value);
                    ViewBag.Situaciones = BaseGlobal.GetSituacion(Convert.ToInt32(lotbAcademicoModel.cnID_Grado));
                }
            }

            //--------------------
            ViewBag.action = a;
            ViewBag.id = i;

            int IdCandidato = Convert.ToInt32(BaseGlobal.CandidatoActual.cnID_Candidato);
            ViewBag.document = lotbAcademicoBLL.ListDoceumnts(IdCandidato, 1);
            //--------------------

            lotbAcademicoModel.tbAcademicoModelList = lotbAcademicoBLL.GetBycnID_Candidato(cnID_Candidato);

            return View(lotbAcademicoModel);
        }

        [HttpPost]
        public ActionResult SaveAcademica(tbAcademicoModel model, HttpPostedFileBase txtCertificado)
        {
            try
            {
                string fileName = string.Empty;
                string oldFile = model.ctCertificado;
                bool isnewFile = false;
                //if (txtCertificado != null)
                //{
                    if (BaseUtil.SaveFile(txtCertificado, BaseVars.CARPETA_CERTIFICADOS, out fileName))
                    {
                        model.ctCertificado = fileName;
                        isnewFile = true;
                    }
                //}

                tbAcademicoBLL lotbAcademicoBLL = new tbAcademicoBLL();

                model.cfFechaCreacion = DateTime.Now;
                model.ctIPAcceso = BaseUtil.GetIPAddress();
                if (model.cnID_Academico == 0)
                    model.cnID_Academico = lotbAcademicoBLL.Insert(model);
                else
                {
                    if (isnewFile)
                        BaseUtil.DeleteFile(BaseVars.CARPETA_CERTIFICADOS, oldFile);

                    lotbAcademicoBLL.Update(model);

                }

            }
            catch
            {
            }

            return RedirectToAction("Academica", new { a = "saved", i = model.cnID_Academico });
        }

        [HttpPost]
        public ActionResult SaveAcademicaBloque(tbAcademicoModel model, HttpPostedFileBase txtCertificado, int idbloque = 1)
        {
            try
            {
                string fileName = string.Empty;
                string oldFile = model.ctCertificado;
                bool isnewFile = false;
                //if (txtCertificado != null)
                //{
                if (BaseUtil.SaveFile(txtCertificado, BaseVars.CARPETA_CERTIFICADOS, out fileName))
                {
                    model.ctCertificado = fileName;
                    isnewFile = true;
                }
                //}

                tbAcademicoBLL lotbAcademicoBLL = new tbAcademicoBLL();

                //model.cfFechaCreacion = DateTime.Now;
                model.ctIPAcceso = BaseUtil.GetIPAddress();
                if (model.cnID_Academico == 0)
                    model.cnID_Academico = lotbAcademicoBLL.InsertBloque(model, idbloque);
                else
                {
                    if (isnewFile)
                        BaseUtil.DeleteFile(BaseVars.CARPETA_CERTIFICADOS, oldFile);

                    lotbAcademicoBLL.Update(model);

                }

            }
            catch
            {
            }

            return RedirectToAction("Academica", new { a = "saved", i = model.cnID_Academico });
        }

        [HttpPost]
        public ActionResult DeleteFormacion(int id)
        {
            try
            {
                tbAcademicoBLL lotbAcademicoBLL = new tbAcademicoBLL();
                tbAcademicoModel lotbAcademicoModel = lotbAcademicoBLL.GetBycnID_Academico(id);
                lotbAcademicoBLL.Delete(id);
                BaseUtil.DeleteFile(BaseVars.CARPETA_CERTIFICADOS, lotbAcademicoModel.ctCertificado);
                return Json("OK");
            }
            catch
            {
                return Json("KO");
            }
        }

        [HttpPost]
        public ActionResult DeleteFormacionTemporal(int id)
        {
            try
            {
                tbAcademicoBLL lotbAcademicoBLL = new tbAcademicoBLL();
                //tbAcademicoModel lotbAcademicoModel = lotbAcademicoBLL.GetBycnID_Academico(id);
                lotbAcademicoBLL.DeleteByCandidato(id);
                //BaseUtil.DeleteFile(BaseVars.CARPETA_CERTIFICADOS, lotbAcademicoModel.ctCertificado);
                return Json("OK");
            }
            catch
            {
                return Json("KO");
            }
        }

        public ActionResult Complementarios(int? id, string a = null, int? i = null)
        {
            if (!BaseGlobal.IsLogged)
                return this.RedirectToLogin();

            long cnID_Candidato = BaseGlobal.CandidatoActual.cnID_Candidato;
            ViewBag.Grados = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.Grado);
            ViewBag.Carreras = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.Carrera);

            var instituciones = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.Instituto);
            instituciones.AddRange(BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.Universidad));
            instituciones.Sort((x, y) => x.Text.CompareTo(y.Text));
            instituciones.RemoveAll(x => x.Value.Trim() == string.Empty && x.Text == BaseGlobal._ComboSeleccionar);
            instituciones.Insert(0, new SelectListItem() { Text = BaseGlobal._ComboSeleccionar, Value = string.Empty });
            instituciones.Insert(1, new SelectListItem() { Text = BaseGlobal._ComboOtros, Value = BaseGlobal.Otros.ToString() });
            ViewBag.Instituciones = instituciones;

            ViewBag.Situaciones = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.Situacion);
            ViewBag.Paises = BaseGlobal.GetPaisListItem();
            ViewBag.TipoEstudios = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.TipoEstudio);

            tbComplementarioBLL lotbComplementarioBLL = new tbComplementarioBLL();
            tbComplementarioModel lotbComplementarioModel = new tbComplementarioModel();
            lotbComplementarioModel.cfFechaInicio = DateTime.Now;
            lotbComplementarioModel.cfFechaFin = DateTime.Now;
            lotbComplementarioModel.cnID_Candidato = cnID_Candidato;
            lotbComplementarioModel.tbComplementarioModelList = new List<tbComplementarioModel>();

            if (id.HasValue)
            {
                if (id.Value > 0)
                {
                    lotbComplementarioModel = lotbComplementarioBLL.GetBycnID_Complementario(id.Value);
                }
            }

            lotbComplementarioModel.tbComplementarioModelList = lotbComplementarioBLL.GetBycnID_Candidato(cnID_Candidato);

            //--------------------
            ViewBag.action = a;
            ViewBag.id = i;
            //--------------------

            return View(lotbComplementarioModel);
        }

        [HttpPost]
        public ActionResult SaveComplementario(tbComplementarioModel model, HttpPostedFileBase txtCertificado)
        {
            try
            {
                string fileName = string.Empty;
                string oldFile = model.ctCertificado;
                bool isnewFile = false;
                if (txtCertificado != null)
                {
                    if (BaseUtil.SaveFile(txtCertificado, BaseVars.CARPETA_CERTIFICADOS, out fileName))
                    {
                        model.ctCertificado = fileName;
                        isnewFile = true;
                    }
                }

                tbComplementarioBLL lotbComplementarioBLL = new tbComplementarioBLL();

                model.cfFechaCreacion = DateTime.Now;
                model.ctIPAcceso = BaseUtil.GetIPAddress();
                if (model.cnID_Complementario == 0)
                    model.cnID_Complementario = lotbComplementarioBLL.Insert(model);
                else
                {

AppSeleccion/mvcSeleccion/Views/Formacion/Complementarios.cshtml
@model SalarDb.CodeGen.Model.tbComplementarioModel
@using System.Linq;
@{
    Layout = BaseGlobal._Layout;
}
@section view_scripts{
    <script type="text/javascript" src="@Url.Content("~/Scripts/view/Academica.js")"></script>
}

<section class="content-header">

    <h1>@*Estudios Complementarios*@</h1>

    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li class="active">Estudios Complementarios</li>
    </ol>
</section>
<section class="content">
    @using (Html.BeginForm("SaveComplementario", "Formacion", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
    {
        @Html.HiddenFor(model => model.cnID_Complementario)
        @Html.HiddenFor(model => model.cnID_Candidato)
        @Html.HiddenFor(model => model.ctCertificado)

        <div class="box-body">
            <div class="panel panel-info">
                <div class="panel-heading"><h3>Datos complementarios</h3></div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cnID_TipoEstudio">Tipo de Estudio:</label>
                                @Html.DropDownListFor(model => model.cnID_TipoEstudio, (List<SelectListItem>)ViewBag.TipoEstudios, new { @class = "form-control", placeholder = "Grado", required = "required" })
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="ctTipoEstudioOtro">Descripción:</label>
                                @Html.TextBoxFor(model => model.ctDescripcion, new { @class = "form-control text-uppercase", placeholder = "Descripción", required = "required", maxlength = "20" })

                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="cnID_Situacion">Situación:</label>
                                @Html.DropDownListFor(model => model.cnID_Situacion, (List<SelectListItem>)ViewBag.Situaciones, new { @class = "form-control", placeholder = "Situación", required = "required" })
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label for="cnID_Institucion">Institución:</label>
                                @Html.DropDownListFor(model => model.cnID_Institucion, (List<SelectListItem>)ViewBag.Instituciones, new { @class = "form-control", placeholder = "Grado", required = "required" })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="ctInstitucionOtro">Institución Otro:</label>
                                @Html.TextBoxFor(model => model.ctInstitucionOtro, new { @class = "form-control text-uppercase", placeholder = "Otro", pattern = "^[a-zA-Z ]+$", required = "required", maxlength = "200" })
                                <span class="help-block">Sólo se permiten letras</span>
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label for="cnID_Pais">País:</label>
                                @Html.DropDownListFor(model => model.cnID_Pais, (List<SelectListItem>)ViewBag.Paises, new { @class = "form-control", placeholder = "Grado", required = "required" })
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="cfFechaNacimiento">Desde:</label>
                                <div class='input-group date' id='txtFechaInicioContainer'>
                                    @Html.TextBoxFor(model => model.cfFechaInicio, new { @class = "form-control", placeholder = "Fecha Inicio", required = "required" })
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="cfFechaNacimiento">Hasta:</label>
                                <div class='input-group date' id='txtFechaFinContainer'>
                                    @Html.TextBoxFor(model => model.cfFechaFin, new { @class = "form-control", placeholder = "Fecha Fin", required = "required" })
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                    @*<div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="cnID_Institucion">Descripción:</label>
                                    @Html.TextBoxFor(model => model.ctDescripcion, new { @class = "form-control", placeholder = "Descripción", required = "required" })
                                </div>
                            </div>

                        </div>*@

                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group" id="divCargarArchivo">
                                <label for="ctApellidoPaterno">Certificado de Estudio <span class="text-danger">(Sólo formato PDF y con tamaño máximo de 3mb)</span>:</label>

                                @if (Model.cnID_Complementario > 0)
                                {
                                    @*@Html.ActionLink("Descargar", "DownloadFile", "Seleccion", new { file = Model.ctCertificado }, new { target = "_blank", @class = "btn btn-link" })*@
                                    <a href="#" class="btn btn-link" id="lnkDescargar" data-filename="@Model.ctCertificado">Ver</a>
                                }

                                <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                    <div class="form-control" data-trigger="fileinput"><i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span></div>
                                    <span class="input-group-addon btn btn-default btn-file"><span class="fileinput-new">Seleccionar</span><span class="fileinput-exists">Cambiar</span><input type="file" name="txtCertificado"></span>
                                    <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Eliminar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @if (Model.cnID_Complementario == 0)
                {
                    <div class="row">
                        <div class="col-md-12">

                            <table class="table table-striped table-hover" id="tab_logic">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th></th>
                                        <th>Tipo Estudio</th>
                                        <th>Descripción</th>
                                        <th>Desde</th>
                                        <th>Hasta</th>
                                        <th>Situación</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @for (int i = 0; i < Model.tbComplementarioModelList.Count(); i++)
                                    {
                                        var item = Model.tbComplementarioModelList[i];
                                        <tr id="row_id_@item.cnID_Complementario">
                                            <td data-title="Eliminar" class='deleterow' onclick="removeRow(this,@item.cnID_Complementario)"><div class='glyphicon glyphicon-remove' title="Eliminar"></div></td>
                                            <td data-title="Editar" class='editrow' onclick="editRow(@item.cnID_Complementario)"><div class='glyphicon glyphicon-edit' title="Editar"></div></td>
                                            <td data-title="Tipo Estudio">@(((List<SelectListItem>)ViewBag.TipoEstudios).Find(x => x.Value == item.cnID_TipoEstudio.ToString()).Text)</td>
                                            <td data-title="Descripción">@item.ctDescripcion</td>
                                            <td data-title="Desde">@item.cfFechaInicio.ToShortDateString()</td>
                                            <td data-title="Hasta">@item.cfFechaFin.ToShortDateString()</td>
                                            <td data-title="Situación">@(((List<SelectListItem>)ViewBag.Situaciones).Find(x => x.Value == item.cnID_Situacion.ToString()).Text)</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                }
                <div class="box-footer text-center">

                    <button type="reset" class="btn btn-default" id="btnCancelar">Cancelar</button>
                    <button type="submit" class="btn btn-primary" id="btnGuardar">Guardar</button>
                </div>
            </div>
        </div>

    }
</section>
@Html.Hidden("hdnDownloadFileUrl", @Url.Content("~/Seleccion/DownloadFile"))

@section inpage_scripts{
    <script type="text/javascript">
        function removeRow(obj, _id) {
            //alert(_id);
            if (_id > 0) {
                bootboxConfirm('¿Está seguro de eliminar el registro?', function () {
                    $.post('@Url.Content("~/Formacion/DeleteComplementario")', { id: _id },
                        function (resp) {
                            ShowResponseDelete(resp);
                            var $killrow = $(obj).parent('tr');
                            $killrow.addClass("danger");
                            $killrow.fadeOut(100, function () {
                                $(this).remove();
                            });
                        });
                });
            }
            else {


                var $killrow = $(obj).parent('tr');
                $killrow.addClass("danger");
                $killrow.fadeOut(100, function () {
                    $(this).remove();
                });
            }
        }


        function editRow(_id) {
            var url = '@Url.Content("~/Formacion/Complementarios/")';
            location.href = url + _id;
        }

        $("#btnCancelar").click(function () {
            var url = '@Url.Content("~/Formacion/Complementarios/")';
            location.href = url;
        });

        @if (ViewBag.action == "saved")
          {
              <text>
        ShowResponse("OK");
        SelectRow('tab_logic', 'row_id_' + @ViewBag.id);
        </text>
          }


        @*@if(Model.cnID_Complementario>0)
        {
            <text>
        $('form').data('formValidation').enableFieldValidators('txtCertificado', false);

        </text>
        }*@

        @if(Model.cnID_Complementario==0)
         {
             <text>
        $("#cfFechaInicio").val("");
        $("#cfFechaFin").val("");
        </text>
         }


        $("#cnID_Institucion").change(function()
        {
            var enabled=false;

            if($("#cnID_Institucion").val()=="@BaseGlobal.Otros")
            {
                enabled=true;
            }

            if(enabled)
            {
                $("input[name=ctInstitucionOtro]").attr("required","required");
                $('form').formValidation('addField',$("input[name=ctInstitucionOtro]"));
                $('form').formValidation('revalidateField', 'ctInstitucionOtro');
            }
            else
            {
                $("input[name=ctInstitucionOtro]").removeAttr("required");
                $("input[name=ctInstitucionOtro]").parent().removeClass("has-error");
                $('form').formValidation('removeField',$("input[name=ctInstitucionOtro]"));
                $('form').formValidation('revalidateField', 'ctInstitucionOtro');
            }

        });

    </script>
}