AppSeleccion/mvcSeleccion/Controllers/ConvocatoriaController.cs
using SalarDb.CodeGen.BLL;
using SalarDb.CodeGen.Common;
using SalarDb.CodeGen.Model;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using mvcSeleccion.Globals;
using OfficeOpenXml;

namespace mvcSeleccion.Controllers
{
    [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)]
    public class ConvocatoriaController : WebControllerBase
    {
        // GET: Convocatoria
        public ActionResult Index(string a = null, int? i = null)
        {
            if (!BaseGlobal.IsLogged)
                return this.RedirectToLogin();

            List<tbProcesoModel> lotbProcesoModelList = new List<tbProcesoModel>();
            tbProcesoBLL lotbProcesoBLL = new tbProcesoBLL();

            lotbProcesoModelList = lotbProcesoBLL.GetAll();

            //--------------------
            ViewBag.action = a;
            ViewBag.id = i;
            //--------------------

            return View(lotbProcesoModelList);
        }

        public ActionResult Detalle(string a = null, long? i = null)
        {
            if (!BaseGlobal.IsLogged)
                return this.RedirectToLogin();

            tbProcesoModel lotbProcesoModel = new tbProcesoModel();
            tbProcesoBLL lotbProcesoBLL = new tbProcesoBLL();

            lotbProcesoModel.cfFechaFin = DateTime.Now;
            lotbProcesoModel.cfFechaInicio = DateTime.Now;

            ViewBag.action = a;

            if (i > 0)
            {
                lotbProcesoModel = lotbProcesoBLL.GetBycnID_Proceso(i.Value);

                tbProcesoCoberturaBLL lotbProcesoCoberturaBLL = new tbProcesoCoberturaBLL();
                lotbProcesoModel.tbProcesoCoberturaList = lotbProcesoCoberturaBLL.GetBycnID_Proceso(i.Value);

                tbProcesoCnfgAcadBLL lotbProcesoCnfgAcadBLL = new tbProcesoCnfgAcadBLL();
                lotbProcesoModel.tbProcesoCnfgAcadModelList = lotbProcesoCnfgAcadBLL.GetBycnID_Proceso(i.Value);

                tbProcesoCnfgLaboBLL lotbProcesoCnfgLaboBLL = new tbProcesoCnfgLaboBLL();
                var confLabo = lotbProcesoCnfgLaboBLL.GetBycnID_Proceso(i.Value);
                if (confLabo.Count > 0)
                    lotbProcesoModel.tbProcesoCnfgLabo = confLabo.First();
                else
                    lotbProcesoModel.tbProcesoCnfgLabo = new tbProcesoCnfgLaboModel();

                tbProcesoCriterioAdicBLL lotbProcesoCriterioAdicBLL = new tbProcesoCriterioAdicBLL();
                lotbProcesoModel.tbProcesoCriterioAdicModelList = lotbProcesoCriterioAdicBLL.GetBycnID_Proceso(i.Value);

                tbProcesoDocumentoBLL LOtbProcesoDocumentoBLL = new tbProcesoDocumentoBLL();
                lotbProcesoModel.tbProcesoDocumentoModelList = LOtbProcesoDocumentoBLL.GetBycnID_Proceso(i.Value);
            }

            lotbProcesoModel.tbProcesoCoberturaList = (lotbProcesoModel.tbProcesoCoberturaList == null) ? new List<tbProcesoCoberturaModel>() : lotbProcesoModel.tbProcesoCoberturaList;
            if (lotbProcesoModel.tbProcesoCoberturaList.Count == 0)
                lotbProcesoModel.tbProcesoCoberturaList.Add(new tbProcesoCoberturaModel());

            lotbProcesoModel.tbProcesoCnfgAcadModelList = (lotbProcesoModel.tbProcesoCnfgAcadModelList == null) ? new List<tbProcesoCnfgAcadModel>() : lotbProcesoModel.tbProcesoCnfgAcadModelList;
            if (lotbProcesoModel.tbProcesoCnfgAcadModelList.Count == 0)
                lotbProcesoModel.tbProcesoCnfgAcadModelList.Add(new tbProcesoCnfgAcadModel());

            if (lotbProcesoModel.tbProcesoCnfgLabo == null)
                lotbProcesoModel.tbProcesoCnfgLabo = new tbProcesoCnfgLaboModel();

            lotbProcesoModel.tbProcesoCriterioAdicModelList = (lotbProcesoModel.tbProcesoCriterioAdicModelList == null) ? new List<tbProcesoCriterioAdicModel>() : lotbProcesoModel.tbProcesoCriterioAdicModelList;
            //if (lotbProcesoModel.tbProcesoCriterioAdicModelList.Count == 0)
            //    lotbProcesoModel.tbProcesoCriterioAdicModelList.Add(new tbProcesoCriterioAdicModel());

            lotbProcesoModel.tbProcesoDocumentoModelList = (lotbProcesoModel.tbProcesoDocumentoModelList == null) ? new List<tbProcesoDocumentoModel>() : lotbProcesoModel.tbProcesoDocumentoModelList;
            //if (lotbProcesoModel.tbProcesoDocumentoModelList.Count == 0)
            //    lotbProcesoModel.tbProcesoDocumentoModelList.Add(new tbProcesoDocumentoModel());

            ViewBag.Grados = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.Grado);
            ViewBag.Situaciones = new List<SelectListItem>();
            ViewBag.TipoEntidadListado = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.TipoEntidadConvocatoria);
            ViewBag.EstadosProcesoListado = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.EstadoProceso);

            return View(lotbProcesoModel);
        }

        [HttpGet]
        public ActionResult CriterioLaboralListado(long id)
        {
            tbProcesoCnfgLaboBLL lotbProcesoCnfgLaboBLL = new tbProcesoCnfgLaboBLL();
            List<tbProcesoCnfgLaboModel> tbProcesoCnfgLaboModelList = lotbProcesoCnfgLaboBLL.GetBycnID_Proceso(id);
            return PartialView("ConfigLaboralListado", tbProcesoCnfgLaboModelList);
        }

        [HttpGet]
        public PartialViewResult CriterioLaboralMatriz(int? tipoCriterio, int id, int confLaboral)
        {
            tbProcesoMatrizLaboModel lotbProcesoMatrizLaboModel = new tbProcesoMatrizLaboModel();
            lotbProcesoMatrizLaboModel.tbProcesoMatrizLaboModelList = new List<tbProcesoMatrizLaboModel>();
            lotbProcesoMatrizLaboModel.tbProcesoMatrizLaboModelList.Add(new tbProcesoMatrizLaboModel());

            ViewBag.TipoEvaluacionListado = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.TipoEvaluacion, false);
            ViewBag.TipoCriterioLaboralListado = BaseGlobal.GetMaestroListItem(BaseGlobal.GruposListas.TipoCriterioLaboral);

            //if (tipoCriterio.HasValue)
            //    lotbProcesoMatrizLaboModel.cnID_TipoCriterioLabo = tipoCriterio.Value;

            if (id > 0)
            {
                tbProcesoMatrizLaboBLL lotbProcesoMatrizLaboBLL = new tbProcesoMatrizLaboBLL();
                lotbProcesoMatrizLaboModel = lotbProcesoMatrizLaboBLL.GetBycnID_MatrizLaboral(id);
            }
            lotbProcesoMatrizLaboModel.cnID_CnfgLaboral = confLaboral;

            tbProcesoCnfgLaboBLL lotbProcesoCnfgLaboBLL = new tbProcesoCnfgLaboBLL();
            tbProcesoCnfgLaboModel tbProcesoCnfgLaboModelTmp = new tbProcesoCnfgLaboModel();

            if (confLaboral > 0)
                tbProcesoCnfgLaboModelTmp = lotbProcesoCnfgLaboBLL.GetBycnID_CnfgLaboral(confLaboral);

            if (tipoCriterio.HasValue)
                tbProcesoCnfgLaboModelTmp.cnID_TipoCriterioLabo = tipoCriterio.Value;

            ViewBag.tbProcesoCnfgLaboModel = tbProcesoCnfgLaboModelTmp;

            return PartialView("_CriterioLaboralMatriz", lotbProcesoMatrizLaboModel);
        }

        [HttpGet]
        public PartialViewResult MatrizLaboralListado(long id, int tipoCriterio = 0, int confLaboral = 0)
        {
            List<tbProcesoMatrizLaboModel> lotbProcesoMatrizLaboModelList = new List<tbProcesoMatrizLaboModel>();
            tbProcesoMatrizLaboBLL lotbProcesoMatrizLaboBLL = new tbProcesoMatrizLaboBLL();
            lotbProcesoMatrizLaboModelList = lotbProcesoMatrizLaboBLL.GetBycnID_Proceso(id);
            ViewBag.TipoCriterio = tipoCriterio;

            lotbProcesoMatrizLaboModelList.ForEach(x =>
            {
                tbProcesoCnfgLaboBLL lotbProcesoCnfgLaboBLL = new tbProcesoCnfgLaboBLL();
                x.tbProcesoCnfgLaboModel = lotbProcesoCnfgLaboBLL.GetBycnID_CnfgLaboral(x.cnID_CnfgLaboral);
            });

            return PartialView("_MatrizLaboralListado", lotbProcesoMatrizLaboModelList);
        }

        [HttpPost]
        public ActionResult SaveMatriz(int cnID_MatrizLaboral, int cnID_CnfgLaboral, Int64 cnID_Proceso, Int64 cnID_TipoEntidad, /*Int64 cnID_TipoEvaluacion, */int cnMininmo, int cnMaximo, int cnPuntaje, string ctDescripcion, Int32 cnID_TipoCriterioLabo, string model = null)
        {
            string message = string.Empty;
            try
            {
                tbProcesoMatrizLaboModel lotbProcesoMatrizLaboModel = new tbProcesoMatrizLaboModel();
                lotbProcesoMatrizLaboModel.cnID_MatrizLaboral = cnID_MatrizLaboral;

                //lotbProcesoMatrizLaboModel.cnID_Proceso = cnID_Proceso;
                //lotbProcesoMatrizLaboModel.cnID_TipoEvaluacion = cnID_TipoEvaluacion;
                lotbProcesoMatrizLaboModel.cnMininmo = cnMininmo;
                lotbProcesoMatrizLaboModel.cnMaximo = cnMaximo;
                lotbProcesoMatrizLaboModel.cnPuntaje = cnPuntaje;
                //lotbProcesoMatrizLaboModel.ctDescripcion = ctDescripcion;
                //lotbProcesoMatrizLaboModel.cnID_TipoCriterioLabo = cnID_TipoCriterioLabo;

                IDbConnection con = dbSeleccionDbConnection.GetNewConnection();
                dbSeleccionDbTransaction tran = dbSeleccionDbTransaction.BeginTransaction();
                tran.Connection = con;
                try
                {
                    tbProcesoBLL lotbProcesoBLL = new tbProcesoBLL();
                    tbProcesoMatrizLaboBLL lotbProcesoMatrizLaboBLL = new tbProcesoMatrizLaboBLL();
                    tbProcesoCnfgLaboBLL lotbProcesoCnfgLaboBLL = new tbProcesoCnfgLaboBLL();

                    lotbProcesoMatrizLaboBLL.Transaction = tran;
                    lotbProcesoMatrizLaboBLL.Transaction.Connection = con;

                    lotbProcesoCnfgLaboBLL.Transaction = tran;
                    lotbProcesoCnfgLaboBLL.Transaction.Connection = con;

                    lotbProcesoBLL.Transaction = tran;

AppSeleccion/mvcSeleccion/Views/Convocatoria/AddZonaCobertura.cshtml
@model List<SalarDb.CodeGen.Model.tbCoberturaZonaModel>
@{
    int index = 1;
    long id = ViewBag.CoberturaId;
}
<form role="form" id="frmCoberturaZonas">
    <div class="row">
        <div class="col-md-12">

            <div class="box box-solid">
                <div class="box-body">
                    <table class="table table-striped table-hover" id="tab_zonas">
                        <thead>
                            <tr>

                                <th></th>
                                <th>Zona</th>


                            </tr>
                        </thead>
                        <tbody>
                            @foreach (SalarDb.CodeGen.Model.tbCoberturaZonaModel item in Model)
                            {

                                <tr>
                                    <td data-title="Eliminar" class='deleterow' onclick="removeRowZona(this,@item.cnID_CoberturaZona)"><div class='glyphicon glyphicon-remove' title="Eliminar"></div></td>

                                    <td>
                                        <div class="form-group">
                                            @Html.Hidden("tbCoberturaZonaModelList_cnID_CoberturaZona[]", item.cnID_CoberturaZona, new { id = "tbProcesoCoberturaList_" + index + "_cnID_CoberturaZona" })
                                            @Html.TextBox("tbCoberturaZonaModelList_ctZona[]", item.ctZona, new { @class = "form-control  text-uppercase", id = "tbProcesoCoberturaList_" + index + "_ctZona", required = "required" })
                                        </div>
                                    </td>
                                    <td>
                                        @if (index == 1)
                                        {
                                            <label id="add_row_zona" class="btn btn-primary add_row_zona">
                                                Agregar
                                            </label>
                                        }
                                    </td>
                                </tr>
                                        index++;


                            }
                        </tbody>
                    </table>


                </div>
            </div>
            <div class="box-footer text-center">
                <button type="submit" class="btn btn-primary" id="btnGuardarZonas">Guardar</button>
            </div>
        </div>
    </div>

</form>

<script type="text/javascript">
    $(window).ready(function () {

        var nroFilaZona=@Model.Count;

        $("#add_row_zona").click(function () {

            var $template = $('<tr><td data-title="Eliminar" class="deleterow" onclick="removeRowZona(this,0)"><div class="glyphicon glyphicon-remove" title="Eliminar"></div></td>  <td><div class="form-group"><input id="tbProcesoCoberturaList_'+nroFilaZona+'_cnID_CoberturaZona" name="tbCoberturaZonaModelList_cnID_CoberturaZona[]" type="hidden" value="0"><input class="form-control  text-uppercase" id="tbProcesoCoberturaList_'+nroFilaZona+'_ctZona" name="tbCoberturaZonaModelList_ctZona[]" type="text" value=""></div></td><td></td></tr>');
            $('#tab_zonas tr:last').after($template);

            $('form').formValidation('addField', $template.find('[name="tbCoberturaZonaModelList_ctZona[]"]'));

            nroFilaZona++;
        });





    });

    function removeRowZona(obj, _id) {
        //alert(_id);
        if (_id > 0) {
            bootboxConfirm('¿Está seguro de eliminar el registro?', function () {
                $.post('@Url.Content("~/Convocatoria/DeleteZona")', { id: _id },
                    function (resp) {
                        ShowResponseDelete(resp);
                        var $killrow = $(obj).parent('tr');
                        $killrow.addClass("danger");
                        $killrow.fadeOut(100, function () {
                            $(this).remove();

                            $('form').formValidation('removeField', $(this).find('[name="tbCoberturaZonaModelList_ctZona[]"]'));
                        });
                    });
            });
        }
        else {


            var $killrow = $(obj).parent('tr');
            $killrow.addClass("danger");
            $killrow.fadeOut(100, function () {
                $(this).remove();

                $('form').formValidation('removeField', $(this).find('[name="tbCoberturaZonaModelList_ctZona[]"]'));

            });
        }
    }


    $('#frmCoberturaZonas').formValidation(
            {
                fields: {
                    'tbCoberturaZonaModelList_ctZona[]': {
                        validators: {
                            notEmpty: {
                                message: 'Este campo es requerido'
                            }
                        }
                    }
                }
            })
            .on('err.field.fv', function (e, data) {
                data.element
                    .data('fv.messages')
                    .find('.help-block[data-fv-for="' + data.field + '"]').hide();
            })
        .on('submit', function (e) {


            if (e.isDefaultPrevented()) {
                // handle the invalid form...

            }
            else {

                $.post("@Url.Content("~/Convocatoria/SaveZonas")",
                    {
                        id : @id,
                        'tbCoberturaZonaModelList_cnID_CoberturaZona[]': $('[name="tbCoberturaZonaModelList_cnID_CoberturaZona[]"]').map(function(){return $(this).val();}).get(),
                        'tbCoberturaZonaModelList_ctZona[]': $('[name="tbCoberturaZonaModelList_ctZona[]"]').map(function(){return $(this).val();}).get()
                    },
                    function (resp) {
                        if (resp.result == "OK") {
                            bootbox.hideAll();
                            bootboxAlert('Guardado correctamente');
                           
                        }
                        else {
                            bootboxError("Ha ocurrido un error al iniciar sesión. Verifique si sus datos son válidos.")
                            $("#btnIngresar").removeAttr("disabled");
                        }
                    });
                return false;
            }

        });

</script>

AppSeleccion/mvcSeleccion/Views/Convocatoria/ConfigLaboralListado.cshtml
@model List<SalarDb.CodeGen.Model.tbProcesoCnfgLaboModel>
@{
    var listadoGeneral = Model.FindAll(x => x.cnID_TipoCriterioLabo == BaseGlobal.LaboralGeneral).ToList();
    var listadoEspecifico = Model.FindAll(x => x.cnID_TipoCriterioLabo == BaseGlobal.LaboralEspecifico).ToList();
}

<div class="col-md-8">
    <div class="box box-solid">
        <div class="box-header with-border">
            <i class="fa fa-building"></i>
            <h3 class="box-title">Laboral General</h3>
        </div>
        <div class="box-body">

            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th></th>
                        <th>Descripción</th>
                        @*<th>Descripción</th>*@
                        <th>
                            @if (listadoGeneral.Count == 0)
                            {
                                <button class="btn btn-primary" onclick="AddMatriz(this);" data-tipo-criterio="@BaseGlobal.LaboralGeneral" data-config-laboral="0" type="button">Agregar</button>
                            }

                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < listadoGeneral.Count; i++)
                    {
                        var item = listadoGeneral[i];

                        <tr>
                            <td>@(i + 1)</td>
                            <td>@item.ctDescripcion</td>
                            @*<td>@item.ctDescripcion</td>*@
                            <td>
                                <button class="btn btn-primary" onclick="AddMatriz(this);" data-tipo-criterio="@BaseGlobal.LaboralGeneral" data-config-laboral="@item.cnID_CnfgLaboral" type="button">Modificar</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>


        </div>
    </div>
</div>


<div class="col-md-8">
    <div class="box box-solid">
        <div class="box-header with-border">
            <i class="fa fa-building"></i>
            <h3 class="box-title">Laboral Específico</h3>
        </div>
        <div class="box-body">

            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th></th>
                        <th>Descripción</th>
                        @*<th>Descripción</th>*@
                        <th>
                            @if (listadoEspecifico.Count == 0)
                            {
                                <button class="btn btn-primary" onclick="AddMatriz(this);" data-tipo-criterio="@BaseGlobal.LaboralEspecifico" data-config-laboral="0" type="button">Agregar</button>
                            }

                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < listadoEspecifico.Count; i++)
                    {
                        var item = listadoEspecifico[i];

                        <tr>
                            <td>@(i + 1)</td>
                            <td>@item.ctDescripcion</td>
                            @*<td>@item.ctDescripcion</td>*@
                            <td>
                                <button class="btn btn-primary" onclick="AddMatriz(this);" data-tipo-criterio="@BaseGlobal.LaboralEspecifico" data-config-laboral="@item.cnID_CnfgLaboral" type="button">Modificar</button>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>


        </div>
    </div>
</div>

AppSeleccion/mvcSeleccion/Views/Convocatoria/Detalle.cshtml
@model SalarDb.CodeGen.Model.tbProcesoModel
@using System.Linq;
@{
    Layout = BaseGlobal._Layout;
    string disabled = (Model.cnID_Proceso == 0) ? "disabled" : string.Empty;
}
@section view_scripts{
    <script type="text/javascript" src="@Url.Content("~/Scripts/view/ConvocatoriaDetalle.js")"></script>
}

<section class="content-header">

    <h1>@*Convocatorias*@</h1>

    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li class="active">Convocatorias</li>
    </ol>
</section>
<section class="content">
    <div class="box-body">
        <div class="panel panel-info">
            <div class="panel-heading"><h3>Convocatorias</h3></div>
            <div class="panel-body">



                @using (Html.BeginForm("SaveProceso", "Convocatoria", FormMethod.Post, new { enctype = "multipart/form-data", role = "form", id = "frmPrincipal" }))
                {
                    <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="false">Datos Generales <i class="fa"></i></a></li>

                            <li class="@disabled"><a href="#tab_2" data-toggle="tab" aria-expanded="false">Cobertura <i class="fa"></i></a></li>
                            <li class="@disabled"><a href="#tab_3" data-toggle="tab" aria-expanded="false">Criterios Académicos <i class="fa"></i></a></li>
                            <li class="@disabled"><a href="#tab_4" data-toggle="tab" aria-expanded="true">Criterios Laborales <i class="fa"></i></a></li>
                            <li class="@disabled"><a href="#tab_5" data-toggle="tab" aria-expanded="true">Criterios Adicionales <i class="fa"></i></a></li>
                            <li class="@disabled"><a href="#tab_6" data-toggle="tab" aria-expanded="true">Documentos <i class="fa"></i></a></li>

                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab_1">
                                @Html.Partial("_DatosGenerales", Model)
                            </div><!-- /.tab-pane -->
                            @if (Model.cnID_Proceso > 0)
                            {
                                <div class="tab-pane" id="tab_2">
                                    @Html.Partial("_Cobertura", Model)
                                </div><!-- /.tab-pane -->
                                <div class="tab-pane" id="tab_3">
                                    @Html.Partial("_CriteriosAcademicos")
                                </div><!-- /.tab-pane -->
                                <div class="tab-pane " id="tab_4">
                                    @Html.Partial("_CriteriosLaborales", Model.tbProcesoCnfgLabo)
                                </div><!-- /.tab-pane -->
                                <div class="tab-pane " id="tab_5">
                                    @Html.Partial("_CriteriosAdicionales", Model.tbProcesoCriterioAdicModelList)
                                </div><!-- /.tab-pane -->
                                <div class="tab-pane " id="tab_6">
                                    @Html.Partial("_Documentos", Model.tbProcesoDocumentoModelList)
                                </div><!-- /.tab-pane -->
                            }
                        </div><!-- /.tab-content -->
                    </div>
                    <div class="box-footer text-center">
                        <button type="reset" class="btn btn-default" id="btnCancelar">Cancelar</button>
                        <button type="submit" class="btn btn-primary" id="btnGuardar">Guardar</button>
                    </div>

                }
            </div>
        </div>
    </div>
</section>

@section inpage_scripts{

    <script type="text/javascript">
    nroFilaAcademico = @Model.tbProcesoCnfgAcadModelList.Count;
    nroFilaCobertura = @Model.tbProcesoCoberturaList.Count;
    nroFilaCriterioAdicional = @Model.tbProcesoCriterioAdicModelList.Count;
    nroFilaConfDocum = @Model.tbProcesoDocumentoModelList.Count;

    @for (int i = 0; i < Model.tbProcesoCnfgAcadModelList.Count; i++)
         {
            <text>
    $("#@("tbProcesoCnfgAcadModelList_" + i + "_cnID_Grado")").val("@Model.tbProcesoCnfgAcadModelList[i].cnID_Grado");
    $("#@("tbProcesoCnfgAcadModelList_" + i + "_cnID_Situacion")").val("@Model.tbProcesoCnfgAcadModelList[i].cnID_Situacion");
    </text>
        }


    $("#btnCancelar").click(function () {
        var url = '@Url.Content("~/Convocatoria/Index")';
        location.href = url;
    });



    //function loadMatrizGrids(main, popup,tipoCriterio)
    //{
    //    if(popup){
    //        $.get($("#hdnMatrizListadoUrl").val(), { ShortGrid: false ,id: $("#cnID_Proceso").val(),tipoCriterio: tipoCriterio}, function (result) {
    //            $("#divMatrizLaboralListado").html(result);
    //        });
    //    }
    //    if(main){
    //        $.get($("#hdnMatrizListadoUrl").val(), { ShortGrid: true,id: $("#cnID_Proceso").val() }, function (result)
    //        {
    //            $("#divMatrizLaboralListadoMain").html(result);
    //        });
    //    }
    //}

    //loadMatrizGrids(true,false);

    function loadCriteriosLaborales(){


        $.get($("#hdnCiterioLaboralListadoUrl").val(), { id: $("#cnID_Proceso").val()}, function (result) {
            $("#divCriteriosLaborales").html(result);
        });
    }

    $(window).ready(function () {
        @for (int i = 0; i < Model.tbProcesoDocumentoModelList.Count; i++)
            {
                  <text>
        $("#@("tbProcesoDocumentoModelList_" + i + "_cnIndObligatorio")").val("@Model.tbProcesoDocumentoModelList[i].cnIndObligatorio.ToString().ToLower()");
        </text>
            }

    })



    @if(Model.cnID_Proceso>0)
        {
              <text>
    //$('form').formValidation('removeField', $("input[name=txtArchivoTerminos]"));
    //$('form').formValidation('removeField', $("input[name=txtArchivoProceso]"));

    //$("input[name=txtArchivoTerminos]").removeAttr("required");
    //$("input[name=txtArchivoProceso]").removeAttr("required");


    $('form').data('formValidation').enableFieldValidators('txtArchivoTerminos', false);

    $('form').data('formValidation').enableFieldValidators('txtArchivoProceso', false);

    </text>
        }



    @if(Model.cnID_Proceso==0)
        {
            <text>
    $("#cfFechaInicio").val("");
    $("#cfFechaFin").val("");
    </text>
        }

    @if (ViewBag.action == "saved")
         {
             <text>
    ShowResponse("OK");
    </text>
         }

    loadCriteriosLaborales();







    @for (int i = 0; i < Model.tbProcesoCnfgAcadModelList.Count; i++)
        {
            var item2 = Model.tbProcesoCnfgAcadModelList[i];

            <text>


    $.ajax({
        cache: false,
        type: "GET",
        url: '@Url.Content("~/Data/GetSituacion")',
        data: { "idGrado": @item2.cnID_Grado },
        success: function (data) {

            $("#tbProcesoCnfgAcadModelList_" + @i + "_cnID_Situacion").empty();
            $("#tbProcesoCnfgAcadModelList_" + @i + "_cnID_Situacion").append($('<option></option>').val("").html("Seleccionar"));
            $.each(data, function (id, option) {
                $("#tbProcesoCnfgAcadModelList_" + @i + "_cnID_Situacion").append($('<option></option>').val(option.Value).html(option.Text));
                });

            $("#tbProcesoCnfgAcadModelList_" + @i + "_cnID_Situacion").val(@item2.cnID_Situacion);
            },
            error: function (xhr, ajaxOptions, thrownError) { }
        });
        </text>
        }


    </script>
}

AppSeleccion/mvcSeleccion/Views/Convocatoria/_EvaluacionDocumentos.cshtml
@model List<SalarDb.CodeGen.Model.tbPostulanteDocuModel>
<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th></th>
                    <th>Documento</th>
                    <th>Descarga</th>


                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count; i++)
                {
                    var item = Model[i];

                    <tr>
                        <td>@(i + 1)</td>
                        <td>@item.ctDescripcion</td>
                        <td><a href="#" class="btn btn-link lnkDescargar" data-filename="@item.ctRutaArchivo">Ver</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>
@Html.Hidden("hdnDownloadFileUrl", @Url.Content("~/Seleccion/DownloadFilePostulacion"))

   